a_user_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               sfGuardUser
    module:              aUserAdmin
    prefix_path:         admin/user
    column:              id
    with_wildcard_routes: true

a_group_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               sfGuardGroup
    module:              aGroupAdmin
    prefix_path:         admin/group
    column:              id
    with_wildcard_routes: true

a_permission_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               sfGuardPermission
    module:              aPermissionAdmin
    prefix_path:         admin/permission
    column:              id
    with_wildcard_routes: true

# This needs to be consistent across sites so our 
# pkToolkit:deploy task can contact it
pk_sync:
  url: /pksync/:action
  param:
    module: pkSync